import {
  Heart,
  Users,
  Shield,
  Award,
  Plus,
  Pill,
  DollarSign,
  TrendingUp,
  Activity,
  CreditCard,
  Download,
  User,
  Settings,
  LogOut,
  Bell,
  Search,
  Filter,
  MoreHorizontal,
  Edit,
  Trash2,
  Eye,
  CheckCircle,
  XCircle,
  Clock,
  AlertTriangle,
  Info,
  Mail,
  Phone,
  MapPin,
  Calendar,
  FileText,
  Upload,
  ImageIcon,
  Loader2,
  ChevronDown,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Copy,
  Check,
  X,
  Menu,
  Home,
  BarChart3,
  Package,
  Truck,
  Building2,
  Stethoscope,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  heart: Heart,
  users: Users,
  shield: Shield,
  award: Award,
  plus: Plus,
  pill: Pill,
  revenue: DollarSign,
  subscription: TrendingUp,
  subsciption: TrendingUp, // Keep typo for backward compatibility
  sales: Activity,
  active: CreditCard,
  download: Download,
  user: User,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  search: Search,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  clock: Clock,
  alertTriangle: AlertTriangle,
  info: Info,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  fileText: FileText,
  upload: Upload,
  image: ImageIcon,
  loader: Loader2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  copy: Copy,
  check: Check,
  x: X,
  menu: Menu,
  home: Home,
  barChart: BarChart3,
  package: Package,
  truck: Truck,
  building: Building2,
  stethoscope: Stethoscope,
}
